#     Copyright (C) 2007 William McCune
#     Copyright (C) 2023 LaiTeP and contributors
#
#     This file is part of the LADR Deduction Library.
#
#     The LADR Deduction Library is free software; you can redistribute it
#     and/or modify it under the terms of the GNU General Public License
#     as published by the Free Software Foundation; either version 3 of the
#     License, or (at your option) any later version.
#
#     The LADR Deduction Library is distributed in the hope that it will be
#     useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with the LADR Deduction Library; if not, write to the Free Software
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""
setup.py script based on template generated by py2applet. Modified to fit
project requirements.

Usage:
    python setup.py py2app
"""

import pathlib
import plistlib
from setuptools import setup

# Monkey patch py2app to keep the openSSL certificates out of the bundle
from py2app import recipes

monkey = False
try:
    recipes.sslmod._check = recipes.sslmod.check
    del recipes.sslmod.check
    monkey = True
except:
    print("py2app does not have an OpenSSL recipe.")

# Build the app bundle

APP = ["src/prover9-mace4.py"]
DATA_FILES = [
    "src/Images",
    "src/Samples",
    "src/bin",
    "src/control.py",
    "src/files.py",
    "src/my_setup.py",
    "src/options.py",
    "src/partition_input.py",
    "src/platforms.py",
    "src/utilities.py",
    "src/wx_utilities.py",
]
OPTIONS = {
    "iconfile": "./p9.icns",
    "plist": {
        "NSRequiresAquaSystemAppearance": True,  # Disable dark mode support
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)

# Remove the PythonExecutable key from Info.plist
app_path = pathlib.Path(__file__).parent.joinpath("dist/prover9-mace4.app")
plist_path = app_path.joinpath("Contents/Info.plist")

with open(plist_path, "rb") as f:
    plist = plistlib.load(f)

plist["PythonInfoDict"].pop("PythonExecutable")

with open(plist_path, "wb") as f:
    plistlib.dump(plist, f)

if monkey:
    recipes.sslmod.check = recipes.sslmod._check
    del recipes.sslmod._check
